name: Run Tests

on: push

jobs:
  name: "Job Name"
  test:
    name: Test Solutions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - run: go version


